---
title: "Example 1"
author: "Yordan García Corrales"
date: "26/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Arrays
Age_01 <- c(12,14,15,43,25,34,54,33,21,16,34,18,1)
Age_02 <- c(1,2,3,4,5,12,14,42,13,45,55,65,43)

Age_01 <- sort(Age_01);Age_01
Age_02 <- sort(Age_02);Age_02
```

```{r}
#How many people are not adults?
v01<-Age_01<18; sum(v01)
sum(Age_02<18)
```
```{r}
#How many people are adults?
v02<-Age_01>=18; sum(v02)
sum(Age_02>=18)
```
```{r}
#Which people are between 15 and 30 years old?

people01<-Age_01>=15 & Age_01<=30

Age_01[people01]

people02<- Age_02>=15 & Age_02<=30
Age_02
Age_02[people02]

```

```{r}
# What are adults?
Adults01<- Age_01>=18; Adults01
Age_01[Adults01]

Adults02<- Age_02>=18; Adults02
Age_02[Adults02]

```
```{r}
# What are not adults?
Young01<- Age_01<18
Age_01[Young01]

Young02<- Age_02<18
Age_02[Young02]
```

```{r}
#Arrays With NA
array03 <- c(10,11,12,13,NA,NA)
sum(array03,na.rm = T) #Remove NA

print("Omit")
array04<- as.vector(na.omit(array03)) #New Array without NA elements
array04

```

```{r}
#Replace NA elements
array03

is.na(array03)
which(is.na(array03))

array05<- replace(array03,which(is.na(array03)),0); array05
sum(array05)
```

```{r}
# Another way to replace NA elements
array03

array06<-array03
array06[is.na(array06)]<-0
array06
```

