---
title: "Formal reports"
author: "Yordan García Corrales"
date: "30/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressWarnings(suppressMessages(library(DT)))
suppressWarnings(suppressMessages(library(dplyr)))
suppressWarnings(suppressMessages(library(tidyr)))
suppressWarnings(suppressMessages(library(htmltools)))
suppressWarnings(suppressMessages(library(xfun)))
```

```{r}
#Visualization
session_info("DT")
```

```{r}
Datas <- mtcars

datatable(head(Datas))
```
## Additions
### Lineas
```{r}
datatable(head(Datas), class = 'cell-border stripe')
```

### Editable
```{r}
datatable(head(Datas), editable = 'cell')
```
### Edite columns
```{r}
# disable means doesn't allow to edit this columns
datatable(head(Datas), 
          editable = list(target = 'row', 
                          disable = list(columns = c(1, 3, 8))))
```
### Delete row names
```{r}
datatable(head(Datas), rownames = FALSE)
```
### Row renames
```{r}
rows= c("F01","F02","F03","F04","F05","F06")
datatable(head(Datas), rownames = rows)
```
### Column renames
```{r}
datatable(head(Datas), colnames = c("Strong" = "hp"))
```

```{r}
#Using row number
datatable(head(Datas), colnames = c("displacement" = 3))
```

```{r}
#Name in the first column
datatable(head(Datas), colnames = c("Branch/Model" = 1))
```

## Manualy reorder by column
```{r}
datatable(Datas, extensions = 'ColReorder', options = list(colReorder = TRUE))
```

## Add title
```{r}
datatable(head(Datas),
  caption = "Table 1: Performance by vehicle in USA")
```

```{r}
datatable(head(Datas),caption =tags$caption(
    style = "caption-side: bottom; text-align: center;",
    "Table 2:",em("Performance by vehicle in USA")))
```
## Filter by *
```{r}
datatable(Datas, filter = "top", 
          options = list(pageLength = 8, #Amount of rows
                         autoWidth = TRUE)) # Dinamic range
```

```{r}
#In the bottom
datatable(Datas, filter = "bottom", options = list(pageLength = 10))
```
## Functions copy,csv, pdf, print, excel
```{r}
datatable(Datas, extensions = 'Buttons', options = list(
    dom = 'Bfrtip',buttons = c("copy", "csv", "pdf", "print", "excel"))) 
```
## Select columns that you don't want to see
```{r}
datatable(Datas,extensions = 'Buttons', 
          options = list(dom = 'Bfrtip', 
                         buttons = I("colvis")))
```
## Select one column
```{r}
table01 <- datatable(Datas, options = list(pageLength = 10)) %>%
  formatStyle(3,  # número de columna
              color = "white", # color letter 
              backgroundColor = "blue", #color
              fontWeight = "bold")# bold letter
table01
```
## Add too a column
```{r}
table02 <- table01 %>% formatCurrency(3, currency = "$", digits = 1)
table02   
```

## Graphic in a row

```{r}
table03 <- table02 %>%   formatStyle(4,background = styleColorBar(Datas$hp, "red"))
table03
```

## Using JavaScript
```{r}
datatable(Datas, options = list(
  initComplete = JS("function(settings, json) {
      $(this.api().table().header()).css({
        'background-color': '#000',
        'color': '#fff'});}")))
```

