---
title: "Map Visualization I"
author: "Yordan García Corrales"
date: "27/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressWarnings(suppressMessages(library(highcharter)))
suppressWarnings(suppressMessages(library(ggplot2)))
suppressWarnings(suppressMessages(library(dplyr)))
```

# USA
```{r}
country <- "countries/us/us-all"

mapdata <- get_data_from_map(download_map_data(country))
glimpse(mapdata)
```

```{r}
set.seed(1234) # para fijar los datos aleatorios

data_fake <- mapdata %>% 
  select(code = `hc-a2`) %>% 
  mutate(value = 1e5 * abs(rt(nrow(.), df = 10)))

glimpse(data_fake)
```
```{r}
hcmap(country, data = data_fake, value = "value",
      joinBy = c("hc-a2", "code"), name = "Fake data",
      dataLabels = list(enabled = TRUE, format = '{point.name}'),
      borderColor = "#0EAD82", borderWidth = 0.1,
      tooltip = list(valueDecimals = 2, valuePrefix = "$", valueSuffix = " USD"))  %>% 
    hc_title( text = "United States Graphic")
```
# Costa Rica
```{r}
Datas <- read.csv2("Censo_2011.csv") #You have to delete accent mark
Datas
```

```{r}
Datas01 <- Datas[,c(1:2)]

country02 <- "countries/cr/cr-all"

mapdata <- get_data_from_map(download_map_data(country02))

mapdata1 <- merge(mapdata,Datas01,by="name",x.all=T)

Datas02 <- mapdata1[,c(1,20)] # 20  is population

glimpse(Datas02)
```

```{r}
hcmap(map=country02, 
      data = Datas02, 
      joinBy = "name", # To compare values and names
      value = "Población",
      name = "Censo 2011",
      dataLabels = list(enabled = T, format = '{point.name}'),
      tooltip = list(valueSuffix = " personas")) %>% 
    hc_title( text = "Population by Province in Costa Rica")
```
## Using disability
```{r}
Datas03 <- Datas[,c(1,10)]

mapdata2 <- merge(mapdata,Datas03,by="name",x.all=T)

Datas04 <- mapdata2[,c(1,20)]

glimpse(Datas04)
```

```{r}
hcmap(map=country02, 
      data = Datas04, 
      joinBy = "name",
      value = "Discapacidad",
      name = "Censo 2011",
      dataLabels = list(enabled = T, format = '{point.name}'),
      tooltip = list(valueSuffix = "%")) %>% 
    hc_title( text = "Disability in CR by province")
```
## Population by province
```{r}
Datas09 <- Datas[,c(1,13)]

mapdata5 <- merge(mapdata,Datas09,by="name",x.all=T)

Datas10 <- mapdata5[,c(1,20)]

glimpse(Datas10)
```

```{r}
hcmap(map=country02, 
      data = Datas10, 
      joinBy = "name",
      value = "Prom_Ocupantes",
      name = "Censo 2011",
      zoom=15,
      dataLabels = list(enabled = T, format = '{point.name}'),
      tooltip = list(valueSuffix = "%")) %>% 
    hc_title(text = "Mean by home",
            margin = 20, align = "center",
           style = list(color = "#08338F", useHTML = TRUE)) %>% 
  
  #Subtitle
  hc_subtitle(text = "Procentaje by province",
              align = "center") %>% 
  hc_legend(align = "center", x = 0, y = -70) %>%
 
  # Colors
  hc_colorAxis(minColor = "white", maxColor = "red") %>% 
  
  # Custome colors
  # hc_colorAxis(minColor = "#8dff20", maxColor = "#095c00") %>% 
  
  # Zoom
  hc_mapNavigation(enabled = T)
```

# Leaflet package

```{r}
suppressWarnings(suppressMessages(library(leaflet)))
suppressWarnings(suppressMessages(library(leaflet.extras)))
suppressWarnings(suppressMessages(library(sp)))
suppressWarnings(suppressMessages(library(readxl)))
suppressWarnings(suppressMessages(library(sf)))
suppressWarnings(suppressMessages(library(Rcpp)))
```

```{r}
BDM <- read_xlsx("Coordenadas_Cantonales.xlsx")
head(BDM)
```

```{r}
#All map
leaflet() %>% addTiles()
```
## Without cluster
```{r}
Map <- leaflet(BDM) %>% addTiles() %>% 
  addProviderTiles(providers$Esri.WorldStreetMap) %>% # type of map

  # Add mark using df.
  addMarkers(data=BDM,
             lng=~Longitud, lat=~Latitud, 
             label=~BDM$conca,
             popup = BDM$conca)

# To show
Map
```
## With cluster
```{r}
Map <- leaflet(BDM) %>% addTiles() %>% addProviderTiles(providers$Esri.WorldStreetMap) %>% # titles

  addMarkers(data=BDM,
             lng=~Longitud, lat=~Latitud, 
             label=~BDM$conca,
             popup = paste0("Name:", BDM$conca),  
  
  # clusters
  clusterOptions = markerClusterOptions()) %>% 
     addDrawToolbar(
    targetGroup='BDM',
    editOptions = editToolbarOptions(selectedPathOptions = selectedPathOptions()))

# Showing
Map
```

## Automatization
```{r}
 tematic_map <- function(B,x,z){ 
   
   # B is a data frame 
   # x is a vector with datas
   # z kind of map
   
 leaflet(B) %>% addTiles() %>% addProviderTiles(z) %>%
  addMarkers(data=B,
             lng=~Longitud, lat=~Latitud, 
             label=~x,
             popup = paste0("Name:", B$x),  clusterOptions = markerClusterOptions()) %>% 
     addDrawToolbar(
    targetGroup='B',
    editOptions = editToolbarOptions(selectedPathOptions = selectedPathOptions()))
 }
```

```{r}
tematic_map(BDM,BDM$conca,providers$Esri.WorldStreetMap)
```

```{r}
tematic_map(BDM,BDM$conca,providers$Esri.DeLorme)
```

## Another example
```{r}
example01 <- leaflet() %>% 
        addTiles() %>% 
        addMarkers(data = BDM,
                label = BDM$conca,
                lng = ~Longitud, lat = ~Latitud,
                labelOptions = 
                    labelOptions(style = list("font-weight" = "normal",
                              padding = "3px 8px"),
                              textsize = "18px")) # Text size

example01
```

## Using circles
```{r}
colors <- colorFactor(c("red", "green", "blue"), domain = unique(BDM$conca))


Cantonal_2 <- leaflet(BDM) %>%
  addTiles() %>%
  addProviderTiles(providers$Stamen.Terrain) %>% # Tipo de mapa
  addMarkers(lng=~Longitud, 
             lat=~Latitud, 
             label=~BDM$conca,
             popup = BDM$conca,  clusterOptions = markerClusterOptions()) %>% 
  addCircleMarkers(
     color = ~colors(BDM$conca),
    lng = ~Longitud, lat = ~Latitud, popup = ~BDM$conca)

Cantonal_2
```

```{r}
Cantonal_3 <- leaflet(BDM) %>%
  addTiles() %>%
  addProviderTiles(providers$Stamen.Toner) %>% # Tipo de mapa.
  addMarkers(lng=~Longitud, 
             lat=~Latitud, 
             label=~BDM$conca,
             popup = BDM$conca,  clusterOptions = markerClusterOptions()) %>% 
  addCircleMarkers(radius = 10, # dimensiones
     color = "red", # Color del circulo
    lng = ~Longitud, lat = ~Latitud, popup = ~conca)
Cantonal_3
```

