---
title: "CDD01_Tarea_02"
author: "Yordan García Corrales"
date: "26/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

1. Crear vectores
```{r}
#V01 = vector dinámico de 10 elementos entre 1 y 25, con reemplazo.
#V02 = vector dinámico de 20 elementos entre 1 y 40, sin reemplazo.
#V03 = vector que surge de la suma de V01 y V02
#V04 = vector que surge de unir los vectores V01 y V02
#V05 = vector que surge de la resta de V01 y V02
#V06 = vector que compara si los valores de V01 y V02 son iguales.
#V07 = vector que compara si los valores de V01 y V02 son distintos.
#V08 = vector que compara si los valores de V02 son menor que V01.
#V09 = vector que compara si los valores de V02 son mayor que V01.
#V10 = vector que compara si los valores de V02 son mayor o igual que V01.
V01=sample(1:25,10,replace=T)
V02=sample(1:40,20)
V03=V01+V02
V04=c(V01,V02)
V05=V01-V02
V06=V01==V02
V07=V01!=V02
V08=V02<V01
V09=V02>V01
V10=V02>=V01
```

2. Utilizando los datos de V03, responda las siguientes preguntas de su jefatura
```{r}
#a. ¿Requiero los valores separados de la suma, mínimo, máximo, promedio,mediana, desviación estándar y varianza?
print("Datos basados en V03")
sum(V03)
min(V03)
max(V03)
mean(V03)
median(V03)
sd(V03)
var(V03)
```

```{r}
#b. Para responder lo siguiente, primero ordene V03 de forma ascendente.
V03<-sort(V03)

#i. ¿Cuáles son los valores con las posiciones 1, 3, 6, 9 y 10?
V03
V03[c(1,seq(from=3,to=9,3),10)]

#ii. ¿Ocupo un nuevo vector con todos los datos, y adicionalmente el
# promedio, el máximo y el mínimo del original?
print("No ya que el vector V03 mantiene los mismo datos, lo que cambió fue el orden")

#¿Se ocupa un nuevo vector con solo los datos de las posiciones 3, 4, 6,
#, 10, 11 y 12?
V11<-V03[c(3,4,6,10,11,12)]; V11
```
```{r}
#c. Para responder lo siguiente, considere que el total se obtiene de la #suma de los datos

#i. ¿Cuál es la frecuencia acumulada absoluta de los datos?
print("V03")
V03
print("Frecuencia acumulada absoluta")
cumsum(V03)

#ii. ¿Cuál es la frecuencia acumulada relativa de los datos?
print("Frecuencia Absoluta") #Cuanta cuando está repetido cada dato
FrecuenciaAbsoluta=table(V03); FrecuenciaAbsoluta

print("Frecuencia relativa") #FrecuenciaAbsoluta/length(V03)
FrecuenciaRelativa=FrecuenciaAbsoluta/length(V03); FrecuenciaRelativa

print("Frecuencia acumulada absoluta")
cumsum(FrecuenciaRelativa)
```

3. Utilizando los datos de V04 debe crear en todos los casos, vectores que ayuden a
responder las siguientes preguntas de su jefatura
```{r}
#a. ¿Cuáles valores se encuentran en las posiciones 1, 3, 4, 6 y 8?
VA<-V04[c(1,3,4,6,8)]; VA

#b. ¿Cómo hago para tener los resultados de la suma, mínimo, máximo,
#promedio, mediana, desviación estándar y varianza y verlas agrupadas?
VB<-c(sum(V04),min(V04),max(V04),mean(V04),median(V04),sd(V04),var(V04)); VB

#c. ¿Cómo se puede obtener un grupo de datos que represente todos los valores
#de V04, pero sin repetirlos y ordenados de menor a mayor?
VC<-sort(unique(V04)); VC

#d. ¿Cuáles valores se encuentran en las posiciones desde la 7 hasta la 2? Se
#requiere que estén agrupadas en orden inverso al que se encuentra en V04.
VD<- sort(V04,decreasing = T); VD
VD[c(7:2)]

#e. ¿Cuáles son los valores del vector menores a 25?
VE<-V04[V04<25]; VE

#f. ¿Cuáles son los valores del vector mayores a 15?
VF<-V04[V04>15]; VF

#g. ¿Cuáles son los valores del vector mayores a 15 y menores a 32?
VG<-V04[V04>15 & V04<32]; VG

```

