---
title: "Control structures"
author: "Yordan García Corrales"
date: "17/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Create a function
```{r}

means<-c(6, 7, 8, 4, 8)

ceditMean<-function(pArray){
  
  generalMean<-mean(pArray)
  if(generalMean<=30){
    print(paste0("Mean:", generalMean, ", ", "ok"))
  }else if(generalMean>30 & generalMean<=45){
    print(paste0("Mean:", generalMean, ", ", "late payment"))
  }else{
    print(paste0("Mean:", generalMean, ", ", "judicial recovery"))
  }
}

ceditMean(means)
ceditMean(c(6, 17, 48, 49, 38))
ceditMean(c(46, 47, 48, 55, 80))
```

#Database from R
```{r}
Database<-head(mtcars);Database
Database$
```
#Function ifelse
```{r}
ifelse(c(1:13)%%2==0,"Even","Odd")

numbers<-1:20

ifelse(numbers%%2==0 & numbers%%3==0,paste0(numbers,": divisible"), paste0(numbers,": Not divisible"))

```


```{r}
num <- c(0, 1, 0, 0, 0, 1, 1)

# Opción usando el igual.
num <- ifelse(num == 0, "Man", "Woman")

num
```

