---
title: "Arrays"
author: "Yordan García Corrales"
date: "25/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Arrays functions
v1<-c(1,2,3,4)
v2<-c(5,6,7,8)

v3<-c("Hello","Good bye")
v4<-c(T,F,T,F,T,T)
v5<-c(v1,v2)

mode(v1)#numeric
mode(v2)#numeric
mode(v3)#character
mode(v4)#logical
mode(v5)#numeric

```

```{r}
#vector()
vec1<-vector("numeric",4)
vec1

vec2<-vector("logical",3)
vec2

vec3<-vector("character",4); vec3

vec4<-vector("integer",3);vec4
```

```{r}
#Position
v1;  v1[1] #Number 1 that is in position 1 of v1
v1[1:3] #Range of position

```

```{r}
#Function sample
vectorRandom <- sample(1:30,25)
vectorRandom
vectorRandom[c(2:5,25)] #Print position between 2 and 5, and also 25
vectorRandom[c(1:10,24,25)]
```

```{r}
#Update vector's positions
v1
v1[1]<-20
v1[length(v1)]<-54; v1
v1[1:3]<-3; v1
```
```{r}
#Delete vector's position
v1
v1[-c(2:5)]
v1; v1[-c(2,5)]
```

```{r}
# Arrays
v01 <- c(1,2,3,4,5,6,7,8,9)
v02 <- c(10,11,12,13,14,15)
```

```{r}
#Sum
print("Sum")
sum(v01)
sum(v02)

#Min
print("Min")
min(v01)
min(v02)

#Max
print("Max")
max(v01)
max(v02)

#Mean
print("Mean")
mean(v01)
mean(v02)

#Median
print("Median")
median(v01)
median(v02)

#Standard Deviation
print("Standard Deviation")
sd(v01)
sd(v02)

#Variance
print("Variance")
var(v01)
var(v02)
```

```{r}
# Example
v01 <- c(1,2)
v02 <- c(10,11,12,13,14)

v03<-v01+v02 #Get a problem because the add restart

v01
v02
v03
```

```{r}
print("Subtraction")
v03<-v01-v02 #Get a problem because the add restart
v01;v02;v03

print("Multiplication")
v03<-v01*v02 #Get a problem because the add restart
v01;v02;v03

print("Division")
v03<-v01/v02 #Get a problem because the add restart
v01;v02;v03
```

```{r}
#Some math function with arrays
v01 <- c(3,6.7,9,12)
v02 <- c(12,16,32,19)

print("quotient")
v02
v01
v03<-v02%/%v01; v03

print("Residue")
v02
v01
v03<-v02%%v01; v03


```

```{r}
#Pow 
v01<-c(2:5)
v02<-c(3:6)

v01; v02
v03<-v01**v02
v03
```

```{r}
#Example Arrays
v05 <- c(1,2,3,4,5)
v06 <- c(1,2,5,6,3)

v05; v06
v05>v06
v05<=v06
v05==v06
v05!=v06
```

```{r}
#New Arrays
v09 <- c(2:9,20:40,100:85)
v10 <- 1.45:8.93

valor1 <- 5

evaluar1 <- valor1%in%v10
v10
evaluar1

#Evaluate an array in an array
evaluete02<-v09%in%v10
v10
evaluete02
```

