---
title: "Matrix Class"
author: "Yordan García Corrales"
date: "2/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Create matrix through arrays
vm01 <- c(10,7,1,6,8,3)
vm01

matrix1<-matrix(data=vm01,nrow = 2,ncol = 3,byrow = T); matrix1 #Order by row
```

```{r}
#Order by columns
vm01
matrix2<-matrix(data=vm01,nrow = 3,ncol = 2,byrow = F); matrix2
```

```{r}
#Skip variables
matrix3<-matrix(vm01,2); matrix3 #It is optional to specify data in col #and byrow to create a matrix
```

```{r}
#Rename rows and columns (rownames,colnames)
matrix3
rownames(matrix3)<-c("Row1","Row2")
colnames(matrix3)<-c("Col1","Col2","Col3")
matrix3
```


```{r}
#Matrix Union (rbind, cbind)
matrixUnionRow<-rbind(matrix3,matrix3); matrixUnionRow
rownames(matrixUnionRow)<-c('Row1','Row2','Row3','Row4') #Union by row
matrixUnionRow

matrixUnionCol<-cbind(matrix3,matrix3) #Union by col
colnames(matrixUnionCol)<-c("Col1","Col2","Col3",'Col4','Col5','Col6')


```

```{r}
#Get data from a Matrix
matrix3
matrix3[1,1]
matrix3[2,2]
print('Get all row 2')
matrix3[2,]
print('Get all column 3')
matrix3[,3]
```

```{r}
#Filter by a condition
matrix3
logicalAnswer<- matrix3[,"Col3"]<5; logicalAnswer

matrix3[logicalAnswer,]

```

```{r}
#Get the matrix size in an array
size<-dim(matrix3)
matrix3
print('2 Rows and 3 column')
size #2 Rows and 3 column
```

```{r}
#Sum all elements
matrix3
total<-sum(matrix3); total
```

```{r}
#Sum by column, example Col1 = Col1[1,1]+ Col1[1,2]...
matrix3
array_col<-apply(matrix3,MARGIN = 2,FUN = sum); array_col
```

```{r}
#Sum by row, Row1=Row1[1,1]+ Row1[1,2]+Row1[1,3]+ Row1[1,4]+Row1[1,5]+ Row1[1,6]
matrixUnionCol
array_row<-apply(matrixUnionCol,MARGIN = 1,FUN = sum); array_row 
```

```{r}
#Sort by col (Matrix)
matrixUnionCol
sortMatrix3_by_col<-apply(matrixUnionCol,MARGIN = 2,FUN = sort);sortMatrix3_by_col
```

```{r}
#Sort by row (Matrix)
matrixUnionCol
sortMatrix3_by_row<-apply(matrixUnionCol,MARGIN = 1,FUN = sort)
sortMatrix3_by_row #Sort a row in a vertical way
```

```{r}
# Matrix transpose
matrix3
transposeM<-t(matrix3); transposeM
```


```{r}
#New matrix 5 and 6
matrix5<- matrix(sample(1:10,6),nrow = 2); matrix5

matrix6<-matrix(sample(1:10,6),nrow = 3); matrix6

matrix7<-matrix(sample(1:10,6),nrow = 3); matrix7
```

```{r}
#Multiplication in matrix
matrix6*matrix7

print("Multiplication by %*%")
dim(matrix5)[1] #Rows 
dim(matrix6)[2] #Columns
matrix5%*%matrix6#The matrix6 Rows=3, Matrix6 Columns=3
```

```{r}
#Rename columns and rows 
dim(matrix6)
rownames(matrix6)<-c("Row1","Row2","Row3")
colnames(matrix6)<-c("Col1","Col2")

matrix6

#Change just one name
rownames(matrix6)[2]<-"Two"

matrix6
```

```{r}
matrixUnionCol
array_col<-apply(matrixUnionCol,MARGIN = 2,FUN = sum); array_col


#Add total of rows and columns
finalMatrix<-rbind(matrixUnionCol,array_col)
print('Add total in columns')
finalMatrix
print('Rename last row')
rownames(finalMatrix)[3]<-'Total'; finalMatrix

#Sum by row, Row1=Row1[1,1]+ Row1[1,2]+Row1[1,3]+ Row1[1,4]+Row1[1,5]+ Row1[1,6]
#We count the sum in rows again because we add a new row.
array_row<-apply(finalMatrix,MARGIN = 1,FUN = sum); array_row 

print('Add total in columns')
finalMatrix<-cbind(finalMatrix,array_row); finalMatrix

print('Rename last column')
colnames(finalMatrix)[7]<-'Total'; finalMatrix

```

